// MyOnlineResume/frontend/react-resume/src/components/Identity/index.tsx
import React, { FC, useState } from "react";

import { IdentityProps } from "./interface";
import { ThemeState } from "src/redux/theme/interface";

import {
  IdentityButtonWrapper,
  IdentityData,
  IdentityName,
  IdentityTitle,
  IdentityWrapper,
} from "./styled";

import { setThemeToDark, setThemeToLight, themeStore } from "src/redux/theme";

import { IconButton } from "src/components";

export const Identity: FC<IdentityProps> = ({ name, title }) => {
  const [theme, setTheme] = useState<ThemeState["currentTheme"]>(
    (() => {
      const storedTheme = localStorage.getItem("theme");
      return storedTheme ? (storedTheme as (ThemeState["currentTheme"])) : "dark";
    })
  );

  themeStore.subscribe(() => {
    const newTheme = themeStore.getState();
    setTheme(newTheme.currentTheme);
  });

  const getClicked = (theme: string | null, type: string): boolean =>
    theme === type;

  const handleToggleTheme = (theme: ThemeState["currentTheme"]): void => {
    if (theme === "dark") {
      themeStore.dispatch(setThemeToDark());
    } else if (theme === "light") {
      themeStore.dispatch(setThemeToLight());
    }
  };

  return (
    <>
      <IdentityWrapper>
        <IdentityData>
          <IdentityName id="about-me" data-testid="about-me">{name}</IdentityName>
          <IdentityTitle>{title}</IdentityTitle>
        </IdentityData>
        <IdentityButtonWrapper>
          <IconButton
            testId="dark-mode"
            icon="dark_mode"
            clicked={getClicked(theme, "dark")}
            onClick={() => handleToggleTheme("dark")}
          />
          <IconButton
            testId="light-mode"
            icon="light_mode"
            clicked={getClicked(theme, "light")}
            onClick={() => handleToggleTheme("light")}
          />
        </IdentityButtonWrapper>
      </IdentityWrapper>
    </>
  );
};

// MyOnlineResume/frontend/angular-resume/src/app/identity/identity.component.ts
import { Component, Input, afterNextRender } from '@angular/core';

import { IconButtonComponent } from '@app/icon-button/icon-button.component';

@Component({
  selector: 'app-identity',
  standalone: true,
  imports: [IconButtonComponent],
  templateUrl: './identity.component.html',
  styleUrl: './identity.component.scss'
})
export class IdentityComponent {
  @Input() name: string = '';
  @Input() title: string = '';

  theme: 'dark' | 'light' = 'dark';

  constructor() {
    afterNextRender(() => {
      this.initializeTheme();
    });
  }

  initializeTheme(): void {
    const storedTheme = localStorage.getItem('theme');
    this.theme = storedTheme as 'dark' | 'light' || 'dark';
  }

  handleToggleTheme(theme: 'dark' | 'light'): void {
    this.theme = theme;
    localStorage.setItem('theme', theme);
  }
}

<div class="identity-wrapper">
  <div class="identity-data">
    <h1 id="about-me" class="identity-name">{{ name }}</h1>
    <h4 class="identity-title">{{ title }}</h4>
  </div>
  <div class="identity-button-wrapper">
    <app-icon-button icon="dark_mode" [activated]="theme === 'dark'" (click)="handleToggleTheme('dark')">Dark Mode</app-icon-button>
    <app-icon-button icon="light_mode" [activated]="theme === 'light'" (click)="handleToggleTheme('light')">Light Mode</app-icon-button>
  </div>
</div>
