// MyOnlineResume/frontend/angular-resume/src/app/experience/experience.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Job } from './experience.mode';

import { SkeletonComponent } from '@app/skeleton/skeleton.component';

@Component({
  selector: 'app-experience',
  standalone: true,
  imports: [
    CommonModule,
    SkeletonComponent
  ],
  templateUrl: './experience.component.html',
  styleUrl: './experience.component.scss'
})
export class ExperienceComponent {
  @Input() isLoading: boolean = true;
  @Input() jobs?: Job[];
}

<div class="experience-wrapper" aria-labelledby="experience">
  <h2 class="experience-title">Experiências profissionais</h2>
  <ng-container *ngIf="!isLoading && jobs; else loading">
    <div *ngFor="let job of jobs; let i = index" class="experience-item">
      <h2 class="experience-position">{{ job.position }}</h2>
      <h3 class="experience-company">
        {{ job.company }},
        <span class="experience-company-time">{{ job.startDate }} - {{ job.endDate || 'Present' }}</span>
      </h3>
      <div class="experience-description" [innerHTML]="job.description"></div>
      <div *ngIf="job.technologies" class="experience-badge-wrapper">
        <span *ngFor="let tech of job.technologies" class="experience-badge">{{ tech }}</span>
      </div>
    </div>
  </ng-container>
  <ng-template #loading>
    <div class="experience-item">
      <h2 class="experience-position"><app-skeleton [width]="'100%'" /></h2>
      <h3 class="experience-company">
        <app-skeleton [width]="'100%'" />
        <span class="experience-company-time"><app-skeleton [width]="'80px'" /> - <app-skeleton [width]="'80px'" /></span>
      </h3>
      <div class="experience-description"><app-skeleton [width]="'100%'" [height]="'350px'" /></div>
    </div>
  </ng-template>
</div>

// MyOnlineResume/frontend/react-resume/src/components/Experience/index.tsx
import React, { FC } from "react";
import { ExperienceProps } from "./interface";
import {
  ExperienceBadge,
  ExperienceBadgeWrapper,
  ExperienceCompany,
  ExperienceCompanyTime,
  ExperienceDescription,
  ExperienceItem,
  ExperiencePosition,
  ExperienceTitle,
  ExperienceWrapper,
} from "./styled";

import { Skeleton } from "src/components";

export const Experience: FC<ExperienceProps> = ({ isLoading, jobs }) => {
  return (
    <>
      <ExperienceWrapper aria-labelledby="experience">
        <ExperienceTitle>Experiências profissionais</ExperienceTitle>
        {!isLoading && jobs ? (
          jobs.map(
            (
              {
                position,
                company,
                startDate,
                endDate,
                description,
                technologies,
              },
              index
            ) => (
              <ExperienceItem key={index}>
                <ExperiencePosition>{position}</ExperiencePosition>
                <ExperienceCompany>
                  {company},{" "}
                  <ExperienceCompanyTime>
                    {startDate} - {endDate}
                  </ExperienceCompanyTime>
                </ExperienceCompany>
                <ExperienceDescription
                  dangerouslySetInnerHTML={{ __html: description }}
                />
                {technologies && (
                  <ExperienceBadgeWrapper>
                    {technologies.map((tech, index) => (
                      <ExperienceBadge key={index}>{tech}</ExperienceBadge>
                    ))}
                  </ExperienceBadgeWrapper>
                )}
              </ExperienceItem>
            )
          )
        ) : (
          <ExperienceItem>
            <ExperiencePosition>
              <Skeleton width="100%" />
            </ExperiencePosition>
            <ExperienceCompany>
              <Skeleton />
              <ExperienceCompanyTime>
                <Skeleton width="80px" /> - <Skeleton width="80px" />
              </ExperienceCompanyTime>
            </ExperienceCompany>
            <ExperienceDescription>
              <Skeleton height="350px" />
            </ExperienceDescription>
          </ExperienceItem>
        )}
      </ExperienceWrapper>
    </>
  );
};
