// MyOnlineResume/frontend/angular-resume/src/app/profile/profile.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

import { ProfileContacts } from './profile.mode';
import { TechnologyExperience } from '@app/skills/skills.model';

import { PhotoComponent } from '@app/photo/photo.component';
import { SkillsComponent } from '@app/skills/skills.component';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [
    CommonModule,
    PhotoComponent,
    SkillsComponent
  ],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.scss'
})

export class ProfileComponent {
  @Input() photoUrl!: string;
  @Input() aboutMe!: string;
  @Input() contacts?: ProfileContacts[];
  @Input() skillsLoading: boolean = false;
  @Input() skills!: TechnologyExperience[];
}

<aside class="profile-wrapper">
  <app-photo [src]="photoUrl"></app-photo>
  <h2 class="profile-title-about">Sobre mim</h2>
  <div class="profile-about">{{ aboutMe }}</div>
  <div *ngIf="contacts" class="profile-contacts">
    <p *ngFor="let contact of contacts; let i = index" class="profile-contact">
      {{ contact.title }}: {{ contact.value }}
    </p>
  </div>
  <app-skills [isLoading]="skillsLoading" [skills]="skills"></app-skills>
</aside>

// MyOnlineResume/frontend/react-resume/src/components/Profile/index.tsx
import React, { FC } from "react";
import { ProfileProps } from "./interface";
import {
  ProfileAbout,
  ProfileContact,
  ProfileContacts,
  ProfileTitleAbout,
  ProfileWrapper,
} from "./styled";

import {
  Photo,
  Skills,
} from "src/components";

export const Profile: FC<ProfileProps> = ({
  photoUrl,
  aboutMe,
  contacts,
  skillsLoading,
  skills,
}) => {
  return (
    <>
      <ProfileWrapper>
        <Photo src={photoUrl} />
        <ProfileTitleAbout>Sobre mim</ProfileTitleAbout>
        <ProfileAbout>{aboutMe}</ProfileAbout>
        {contacts && (
          <ProfileContacts>
            {contacts.map(({ title, value }, index) => (
              <ProfileContact key={index}>
                {title}: {value}
              </ProfileContact>
            ))}
          </ProfileContacts>
        )}
        <Skills skills={skills} isLoading={skillsLoading} />
      </ProfileWrapper>
    </>
  );
};
